name: Gradle JAR
on:
  push:
    tags:
    - '**'
  workflow_dispatch:
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: actions/checkout@v3
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Execute Gradle build
        run: ./gradlew build
      - name: Upload Results (Common)
        uses: actions/upload-artifact@v3
        with:
          name: JourneyPAC-Common
          path: common/build/libs
      - name: Upload Results (GForge)
        uses: actions/upload-artifact@v3
        with:
          name: JourneyPAC-Forge
          path: forge/build/libs
      - name: Upload Results (Fabric)
        uses: actions/upload-artifact@v3
        with:
          name: JourneyPAC-Fabric
          path: fabric/build/libs